### ISSUE TITLE
User Documentation (Excluding Lua API)

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx.github.io#20]
Being relatively new (2014) to OpenTX I am still looking for documentation. I find that there is no one place where it is complete or where clarification can be sought and then have the documentation updated. Documentation also evolves with code changes and to cater to different audiences. Having a Business and Systems Analyst background it is my opinion that often there are two (or more audiences).

1. The developers, technically advanced users
2. The common users, the beginner 

The documentation for OpenTX seems to have gotten fragmented along these lines. A new user or even someone like myself with some experience has to go searching amongst different content creators for information.

Some thoughts on adding documenters, improving documentation and locating it.
(I may be using the wrong terms but I hope the general idea is clear.)

**GitHub/GitBook**
- Create a new GitHub linked to the existing GitBook User Manual.This provides a clean separation between user documentation and code and the documenters and the developers.
- Developers interested in documentation can join this new GitHub.
- Developers/Administrators not interested or who don't have time for documentation issues won't have to deal with the added volume of non development related issues that need to be dealt with.
- Use "Issues" to request documentation clarification and additions (forums are still the starting point when a user has questions but over time the more active and advanced users will see that maybe the documentation needs updating and create an issue). https://github.com/opentx/opentx-taranis-manual/issues
- Administrators can then tag issues with say new section, new page in existing section, update existing documentation, needs discussion... Along similar lines to development issues.
- Users can also submit documentation write ups under an open issue, have them discussed, once consensus is achieved administrators then merge the changes.
- Administrators can checkout/take ownership of issues to work on similar to how code is treated. 
- All of the above done under the OpenTX banner.
- A new set of documenters may end up joining just like developers have.
 
**Website**
- Create archive pages and move information related to previous versions to those pages.
- Separate out "official" content and links to community created content or always place official content at the top (not in chronological order).
- Archive links to community content as official content encompasses it

**Comment by projectkk2glider** [comment]
I like your ideas. I am not sure about one thing:

>Create a new GitHub linked to the existing GitBook User Manual.This provides a clean separation between user documentation and code and the documenters and the developers.

What do you mean here? We have one github organization `opentx` under which several independent projects or github repositories are: one is OpenTX code, one is OpenTX manual, and one is OpenTX Lua manual. So there is already a separation in place. What more do you want?

**Comment by RCdiy** [comment]
Oops... yes... I got that wrong... Maybe is shoud have posted under https://github.com/opentx/opentx-taranis-manual 
So how does new issue notification work? 
Who gets notified?
Can you configure which notifications you receive... e.g. If you are not interested in documentation then mute those issues.
Is there a limit to number of Administrators?
If there is a limit then is the limit then are the limits by account github/opentx or by repository github/opentx/manual.... The limit may mean a new account? Else when new developers join the admin team documententation admins may get bumped. (Don't know just brainstorming).

**Comment by kilrah** [comment]
You get notified if you "watch" the repository, so no issues here. There's no limit on github repo contributors. There might be for the publishing/online editor service depending on what that ends up being (seems gitbook need to be replaced).

**Comment by powercycle** [comment]
I have been editing the manual and am happy to address issues.

**Comment by powercycle** [comment]
Additionally, for the time being, I'm using a local copy of gitbook editor and server since the one online seems to now charge to use their service.  I'd be happy to work with you if you'd like to set this up for yourself as well.
