### ISSUE TITLE
Dead link for MEGA2560

### ISSUE THREAD

**Issue by steelman** [opentx/opentx.github.io#28]
The download link at http://www.open-tx.org/2015/04/18/M2560-DIY-radio-documentation is "dead".

**Comment by RCdiy** [comment]
@schwabe how do we fix this?

**Comment by schwabe** [comment]
Replace with this https://github.com/opentx/opentx/tree/2.2/doc/Mega2560

**Comment by schwabe** [comment]
Someone (@kilrah) already did this. closing.
