### ISSUE TITLE
lua reference docs

### ISSUE THREAD

**Issue by unstoppablecarl** [opentx/opentx.github.io#4]
Some of the information in this doc https://docs.google.com/document/d/1ILh9lSW4d05qJD2rSKxep0WnJUfNCcAPCafKZeESweE/edit#heading=h.yi8zf2vndziz is incorrect or out of date. Who is maintaining it? How can I submit changes and updates? Why is this a google doc?

**Comment by projectkk2glider** [comment]
Lua docs are on github now https://github.com/opentx/lua-reference-guide
