### ISSUE TITLE
Request: Rename nightly build folders to YYYY-MM-DD

### ISSUE THREAD

**Issue by JoeB99** [opentx/opentx.github.io#5]
http://jenkins.open-tx.org/nightly-20/

Can we rename the folders so that they use the ISO 8601 standard? This way, the most recent build will be at the bottom of the page, rather than half way down the page.
Also, this is considered good practise when maintaining a list of dates and prevents confusion for those that don't use MM-DD-YYYY date format.

I'm aware that I can sort the folders with "last modified" link.

**Comment by bsongis** [comment]
Done

**Comment by JoeB99** [comment]
I'm still seeing MM-DD-YYYY ?

**Comment by projectkk2glider** [comment]
I guess you will see the result tomorrow with the new folder.

**Comment by bsongis** [comment]
I just started manually a nightly build, it should be ready in a couple of minutes

**Comment by JoeB99** [comment]
Completed.
