### ISSUE TITLE
Sites down

### ISSUE THREAD

**Issue by KnuckleUpFPV** [opentx/opentx.github.io#53]
Php error. Had multiple people check

**Comment by KnuckleUpFPV** [comment]
Still down

**Comment by kilrah** [comment]
Maybe you could say what "sites" you refer to...

**Comment by KnuckleUpFPV** [comment]
Opentx university. Org wasnt working for a while last night either. It came back up. I just assumed the opentx sites in general would be checked. Good to go? 🖒

**Comment by kilrah** [comment]
open-txu has "nothing" to do with us, it's been created and is managed by users.

**Comment by KnuckleUpFPV** [comment]
I guess that's good to know. It's not stated anywhere. It is basically the guide on how to use opentx. Maybe you should get with those guys and change that. Well hopefully they get it back up then. They are extremely helpful.
