### ISSUE TITLE
Feature: Add link to "voices-20.open-tx.org"

### ISSUE THREAD

**Issue by JoeB99** [opentx/opentx.github.io#6]
Please add a link to the additional voices here: "voices-20.open-tx.org" and also a description on how these were created so other sounds can be created in the same voice by users.

**Comment by JoeB99** [comment]
Can anyone tell me what was used to create these please? I need to add a few new ones and i'd like them to match those im already using.

**Comment by bsongis** [comment]
They are generated with SAPI voices. The link is inside Companion.

**Comment by JoeB99** [comment]
Having downloaded 'speaker' (which has a bug, it adds a second of no audio at the end of all files created) and created the voices with the microsoft Anna, the only voice available, they are not the same. 

Where can i find the sapi voices that were used to create the sounds available in this download, e.g. english-american, english-irish, english-english etc as per the zip files?

I'm looking to recreate exactly the voices offered here for download but it seems everything required is not documented and/or not available..

**Comment by kilrah** [comment]
I believe the automated process uses commercial software.
